#Generated by soba https://github.com/justinwoo/soba
{ pkgs ? import <nixpkgs> {} }:

{
    "aff" = pkgs.stdenv.mkDerivation {
      name = "aff";
      version = "v5.1.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-aff.git";
        rev = "390857f9143e1a52f7403d05b14c9ca79d356737";
        sha256 = "19v5psd6jz13gr5yqyx8286b5bpfq1dax51w906y0mqgnfz92yzr";
      };
    };

    "arraybuffer-types" = pkgs.stdenv.mkDerivation {
      name = "arraybuffer-types";
      version = "v2.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-arraybuffer-types.git";
        rev = "505aa3de50a1400e5f2fce4a8e7b1a39abaa8fd9";
        sha256 = "059a8n49yhl46l1b1j2qj4ichzq6dzj29ajkfvw88npzj5w2rshy";
      };
    };

    "arrays" = pkgs.stdenv.mkDerivation {
      name = "arrays";
      version = "v5.3.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-arrays.git";
        rev = "1bca4c0b8904e65d356ed6d8db8d6f7e071132d3";
        sha256 = "0r991qcx69xj07iagjaxkm0ab9qi2pw8cs3qwyybhis7asd6bnz6";
      };
    };

    "avar" = pkgs.stdenv.mkDerivation {
      name = "avar";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-avar.git";
        rev = "17914413130490318a475e9de6a9244aaaa097d2";
        sha256 = "14g05jm2xricy5b9vn4k4lhc9lzi5jvpvv85h10s17kn4wwi9igk";
      };
    };

    "bifunctors" = pkgs.stdenv.mkDerivation {
      name = "bifunctors";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-bifunctors.git";
        rev = "1062425892b4a1c734ec653dded22546e3063b27";
        sha256 = "1bdra5fbkraglqrrm484vw8h0wwk48kzkn586v4y7fg106q1q386";
      };
    };

    "bonjiri" = pkgs.stdenv.mkDerivation {
      name = "bonjiri";
      version = "v0.7.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-bonjiri.git";
        rev = "a4076ff489e9aa8c6caa1a20bd8f3c7356bf597c";
        sha256 = "08jr5vz6d6l6mflvxnb8fhi84lwyps10lmygcsb3gdvmysdq8jhs";
      };
    };

    "calpis" = pkgs.stdenv.mkDerivation {
      name = "calpis";
      version = "v0.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-calpis.git";
        rev = "a1513124ec0c727431a2e0aab82f7de8fb5c8144";
        sha256 = "0npivy7cvg6g58x2xgsg1zr5hagpvd1acrn9bbvr2gi4vjy7x4g7";
      };
    };

    "catenable-lists" = pkgs.stdenv.mkDerivation {
      name = "catenable-lists";
      version = "v5.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-catenable-lists.git";
        rev = "d81b7df30d9879d0bb531b3102fb36f429c2f12e";
        sha256 = "0mbpb8xr9a7a4bvawhki7js5cbv7c0lv0vdwb6r8nmv6b61gzg27";
      };
    };

    "choco-pie" = pkgs.stdenv.mkDerivation {
      name = "choco-pie";
      version = "v5.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-chocopie.git";
        rev = "c842beb9468e8cedb17f7a31b3e8166be05b0856";
        sha256 = "1q3xilbk8chsy3c07jal9j8nmcvmydk0kvdv9nrbffpxqc02n457";
      };
    };

    "console" = pkgs.stdenv.mkDerivation {
      name = "console";
      version = "v4.3.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-console.git";
        rev = "add2bdb8a4af2213d993b728805f1f2a5e76deb8";
        sha256 = "1b2nykdq1dzaqyra5pi8cvvz4dsbbkg57a2c88yi931ynm19nnw6";
      };
    };

    "const" = pkgs.stdenv.mkDerivation {
      name = "const";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-const.git";
        rev = "bc5db27b0ed3947fa5e2074ccbab01236eec3fa4";
        sha256 = "0qbd2aisax52yw6sybdhs7na943cbsd6mylhhgsamrf7hzh6v51p";
      };
    };

    "contravariant" = pkgs.stdenv.mkDerivation {
      name = "contravariant";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-contravariant.git";
        rev = "cb69db0253c2e2ed3fef784dad58f3418a8ee834";
        sha256 = "0dd17lwlybpz4i54cxnqdgy38rjlbw9p7bw1r43is6z3kdc8983a";
      };
    };

    "control" = pkgs.stdenv.mkDerivation {
      name = "control";
      version = "v4.2.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-control.git";
        rev = "8af53eea4ecc7b185776a0f144bcd7106ed08eb1";
        sha256 = "10703zvsnjm5fc74k6wzjsvpsfyc3jci3jxhm7rxf7ymya9z1z53";
      };
    };

    "datetime" = pkgs.stdenv.mkDerivation {
      name = "datetime";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-datetime.git";
        rev = "9e76abe96f45a68eb0bb23d0afd56031a8070bee";
        sha256 = "06ghfvbvd5sd0q014qi8j8glk2g2j9f8z8cwq2318kllp92gz07q";
      };
    };

    "debug" = pkgs.stdenv.mkDerivation {
      name = "debug";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/garyb/purescript-debug.git";
        rev = "b1484b8aac685dc83c1d938d71407495ae2a2259";
        sha256 = "0gwjj80akys0h111i74n429fmny992gx0r4rk1n98gqlqm5cmi21";
      };
    };

    "distributive" = pkgs.stdenv.mkDerivation {
      name = "distributive";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-distributive.git";
        rev = "3a43c0690883816e9ebeac510698423cfff5c174";
        sha256 = "0zbn0yq1vv7fbbf1lncg80irz0vg7wnw9b9wrzxhdzpbkw4jinsl";
      };
    };

    "effect" = pkgs.stdenv.mkDerivation {
      name = "effect";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-effect.git";
        rev = "6caa8e1e162a21eed025613c2c19194b996ef779";
        sha256 = "1vqw5wrdxzh1ww6z7271xr4kg4mx0r3k3mwg18dmgmzj11wbn2wh";
      };
    };

    "either" = pkgs.stdenv.mkDerivation {
      name = "either";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-either.git";
        rev = "8b4b38a729f8e88750b03e5c7baf2b3863ce4742";
        sha256 = "12j7vvjly0bgxidxmb2pflx0zy7x425dnvxk2y1pm66n0hbsq7ns";
      };
    };

    "enums" = pkgs.stdenv.mkDerivation {
      name = "enums";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-enums.git";
        rev = "19800105b556798ea5650f8a01bfe5ea17cfc6eb";
        sha256 = "0qq0pgmq497nfml0y8xb2qdpga5xqp9sqq4ilv1rpyhg1v7nzb6v";
      };
    };

    "event" = pkgs.stdenv.mkDerivation {
      name = "event";
      version = "v1.3.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/paf31/purescript-event.git";
        rev = "af8b8d2e381f423c0b5e739e92668e392e77efce";
        sha256 = "0zzlg4ggzv9s2ipg84wj4qbdib3qn38zdzpr8brv79kvb3f0lnzz";
      };
    };

    "exceptions" = pkgs.stdenv.mkDerivation {
      name = "exceptions";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exceptions.git";
        rev = "9012eb08749e9ccd5da45bdece5d576e5fc0b0db";
        sha256 = "17s0rg9k4phivhx9j3l2vqqfdhk61gpj1xfqy8w6zj3rnxj0b2cv";
      };
    };

    "exists" = pkgs.stdenv.mkDerivation {
      name = "exists";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exists.git";
        rev = "ef53359aebc09bf863800ca86ad1dcd76f0b08ae";
        sha256 = "0bbdbw3jaqyi8dj2d52zvfgx4vl84d8cr6hp43vy8lfjfcbj0wlk";
      };
    };

    "filterable" = pkgs.stdenv.mkDerivation {
      name = "filterable";
      version = "v3.0.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/LiamGoodacre/purescript-filterable.git";
        rev = "b7bff31576261bc66bf29bfeca7679c2b107d68e";
        sha256 = "0pn66mrgrpnlpd1lmywj5f0hbm9mnyjahqj276vz5v2xzlr0q63g";
      };
    };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
      name = "foldable-traversable";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foldable-traversable.git";
        rev = "29d5b873cc86f17e0082d777629819a96bdbc7a1";
        sha256 = "03x89xcmphckzjlp4chc7swrpw347ll5bvr2yp7x9v2jqw2jlyi1";
      };
    };

    "foreign" = pkgs.stdenv.mkDerivation {
      name = "foreign";
      version = "v5.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign.git";
        rev = "3b8f3ae608db339ed5cff35d2017a07efb905b4d";
        sha256 = "15mz2s4f8crkd721z4df2aag4s0wil6fs07cpcmi7dpnkn7a4nab";
      };
    };

    "foreign-object" = pkgs.stdenv.mkDerivation {
      name = "foreign-object";
      version = "v2.0.3";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign-object.git";
        rev = "8a7dc21c48e3e6d31e253b0e58dd95a3bbd7f6e7";
        sha256 = "07wiql59zfj901nk9526b6rykn9m24jjcs8v5dgxbr1c3hiab9n3";
      };
    };

    "free" = pkgs.stdenv.mkDerivation {
      name = "free";
      version = "v5.2.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-free.git";
        rev = "f686f5fc07766f3ca9abc83b47b6ad3da326759a";
        sha256 = "1bwj0ay7q9lm4ir29jy549m05jvaqik1s615biv23y51ngx3fn49";
      };
    };

    "functions" = pkgs.stdenv.mkDerivation {
      name = "functions";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functions.git";
        rev = "c63451ae74f6fba7a4eede5f87208a73c537af77";
        sha256 = "0675k5kxxwdvsjs6a3is8pwm3hmv0vbcza1b8ls10gymmfz3k3hj";
      };
    };

    "functors" = pkgs.stdenv.mkDerivation {
      name = "functors";
      version = "v3.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functors.git";
        rev = "96bcf8a970a40115a76a20d19e50aa3b524adcf3";
        sha256 = "1cnn3zhk6qcyiwbbpvrdqgsbch4qihx2y9d6sv45bvd8kzrbd306";
      };
    };

    "gen" = pkgs.stdenv.mkDerivation {
      name = "gen";
      version = "v2.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-gen.git";
        rev = "36f36f03f082b57e402c27f1513f8935caa54101";
        sha256 = "0pk68cn1s89hql30ydks9gh34gbxg391smi2albx3qvxnfkrpxca";
      };
    };

    "generics-rep" = pkgs.stdenv.mkDerivation {
      name = "generics-rep";
      version = "v6.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-generics-rep.git";
        rev = "aae27ba1de21dda342dcdfc8b3cc5b951bd5b3ec";
        sha256 = "15vchzbcvf6byks90q14lvcwb8hnxqzm2mrlxi7v1f7has4s74kn";
      };
    };

    "globals" = pkgs.stdenv.mkDerivation {
      name = "globals";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-globals.git";
        rev = "3c6251da362312d439a19c0939ae98653a7d4d65";
        sha256 = "150mc0kv0cb5fkx0szicwczjr54bglmlyaynj2grf1r4gnjg967s";
      };
    };

    "identity" = pkgs.stdenv.mkDerivation {
      name = "identity";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-identity.git";
        rev = "1b7938abdc8cb28c0ac5f80f63405d53e3173a8e";
        sha256 = "1scdgbfkphfmapw7p9rnsiynpmqzyvnal2glzj450q51f8g1dhld";
      };
    };

    "integers" = pkgs.stdenv.mkDerivation {
      name = "integers";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-integers.git";
        rev = "3850da9cd96b37c71685b6bc3bf0cb489baefc93";
        sha256 = "17d4bfpnrmbxlc7hhhrvnli70ydaqyr26zgvc9q52a76zgdcb4cf";
      };
    };

    "invariant" = pkgs.stdenv.mkDerivation {
      name = "invariant";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-invariant.git";
        rev = "b704c5bda262719ca5cc88a3f8554edff8f03256";
        sha256 = "1fimpbh3yb7clvqxcdf4yf9im64z0v2s9pbspfacgq5b4vshjas9";
      };
    };

    "js-date" = pkgs.stdenv.mkDerivation {
      name = "js-date";
      version = "v6.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-date.git";
        rev = "f332c15f14322434ddd1945ca2db8040294447bf";
        sha256 = "19qyzbr4a1ca8znbd8gcbz0a801f5p1v238ky3408gdx4ba32zjd";
      };
    };

    "js-timers" = pkgs.stdenv.mkDerivation {
      name = "js-timers";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-timers.git";
        rev = "8206d3d8034357b4665828e52f7ff1b8cb46611e";
        sha256 = "1a8092sli7zqw1wflibhjza1ww21dxl7x7r602iazzwh2g70v4dg";
      };
    };

    "lazy" = pkgs.stdenv.mkDerivation {
      name = "lazy";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lazy.git";
        rev = "5bbd04f507a704f39aa756b5e12ed6665205fe2e";
        sha256 = "156q89l4nvvn14imbhp6xvvm82q7kqh1pyndmldmnkhiqyr84vqv";
      };
    };

    "lcg" = pkgs.stdenv.mkDerivation {
      name = "lcg";
      version = "v2.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lcg.git";
        rev = "596bcb17bd550397735220f919df52bcd0038fe0";
        sha256 = "1851cq2g84jzjbvbmncbivbhaqzj9zv5ni3gs14k04nmx2brxmvj";
      };
    };

    "lists" = pkgs.stdenv.mkDerivation {
      name = "lists";
      version = "v5.4.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lists.git";
        rev = "62900a56f6864638c952575dfd211a1cc55be7da";
        sha256 = "0l0jiqhcjzkg4nv2a6h2vdf4izr9mf7cxc86cq1hf3j4dh6spym1";
      };
    };

    "makkori" = pkgs.stdenv.mkDerivation {
      name = "makkori";
      version = "v1.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-makkori.git";
        rev = "bdd0e3899075b86e860b310fd69353ac80a85a98";
        sha256 = "09i5j2xqp6rjmljc6kbn3h1ybw1j3dfwdl6bxzr0wqk3y14wpdlq";
      };
    };

    "math" = pkgs.stdenv.mkDerivation {
      name = "math";
      version = "v2.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-math.git";
        rev = "8be36d24f9d2d8795adf04791446bbc458297b9b";
        sha256 = "1msmy9w7y6fij62sdc55w68gpwkhm6lhgc8qjisjk4sxx1wdg1rr";
      };
    };

    "maybe" = pkgs.stdenv.mkDerivation {
      name = "maybe";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-maybe.git";
        rev = "81f0397636bcbca28642f62421aebfd9e1afa7fb";
        sha256 = "073wa0d51daxdwacfcxg5pf6ch63n4ii55xm1ih87bxrg8mp52mx";
      };
    };

    "media-types" = pkgs.stdenv.mkDerivation {
      name = "media-types";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-media-types.git";
        rev = "e304498356539547b4ed9a7f79513a847c907962";
        sha256 = "0ykwmxrhmwfy6c5mxjxa43xdf5xqakrqyvr5fn986yad50gjqj75";
      };
    };

    "motsunabe" = pkgs.stdenv.mkDerivation {
      name = "motsunabe";
      version = "v2.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-motsunabe.git";
        rev = "d016e6319fef40119abba726e31d066e7c211875";
        sha256 = "03r81xs0gw5nchm93ap2lpirkng8bzgsb8xc5jxlii4sw8wn8ndh";
      };
    };

    "naporitan" = pkgs.stdenv.mkDerivation {
      name = "naporitan";
      version = "v1.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-naporitan.git";
        rev = "e911d10260897f5dec7caa034604691c7146f7ff";
        sha256 = "0d7krc91cda623ajarnwp5s1d35x4nr18y3095rz97yxw00lajzj";
      };
    };

    "newtype" = pkgs.stdenv.mkDerivation {
      name = "newtype";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-newtype.git";
        rev = "7d85fa6a040208c010b05f7c23af6a943ba08763";
        sha256 = "0qvk9p41miy806b05b4ikbr3if0fcyc35gfrwd2mflcxxp46011c";
      };
    };

    "node-buffer" = pkgs.stdenv.mkDerivation {
      name = "node-buffer";
      version = "v6.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-buffer.git";
        rev = "d279daa1b4bf9fe85d5c3aeb96512df4f12e0bc0";
        sha256 = "0ih2y29srdxgn526fw2v1y95hpivjil44vkl93w6nrqsymki36y0";
      };
    };

    "node-http" = pkgs.stdenv.mkDerivation {
      name = "node-http";
      version = "v5.0.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-http.git";
        rev = "b18d054de436ad589d41acee0aca7f3bd6762aab";
        sha256 = "0jr9mm0kdvkd3nf1g4l8w9p7n16qqji03fg1agxn7hngr4ja43pw";
      };
    };

    "node-streams" = pkgs.stdenv.mkDerivation {
      name = "node-streams";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-streams.git";
        rev = "88740eeda2017d3ddcde50eea59d57c7749d8524";
        sha256 = "12dki2li0d7s54kvcr6gksb5nxf6kzs93gwxnq4bh1flri8p0i7r";
      };
    };

    "node-url" = pkgs.stdenv.mkDerivation {
      name = "node-url";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-url.git";
        rev = "20eecd603124bf07b477f1f2be2135ae99c885fe";
        sha256 = "0qbpdz62psy7hb34hw5rw2x1pq7yhd214ysza0xh46c3nlp0ib9y";
      };
    };

    "nonempty" = pkgs.stdenv.mkDerivation {
      name = "nonempty";
      version = "v5.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-nonempty.git";
        rev = "36ca3b2fa6d98b1c9d2ee05643341e496fbeab57";
        sha256 = "1vz174sg32cqrp52nwb2vz9frrzmdwzzlgl4vc2cm5wlf2anirxj";
      };
    };

    "now" = pkgs.stdenv.mkDerivation {
      name = "now";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-now.git";
        rev = "090feddf7c7dec2a812eca090cd211e87ccad606";
        sha256 = "18h5pif2dy4r7w1xg2zw4mvdqlar9xqp3rawkiavmsc946ncf3zs";
      };
    };

    "nullable" = pkgs.stdenv.mkDerivation {
      name = "nullable";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-nullable.git";
        rev = "8d413f02224b8281bfa8037e45fbbf9fe2e254fd";
        sha256 = "14qaxxga8gqlr4pijyvqycdyhjr6qpz3h4aarficw5j75b7x8nyv";
      };
    };

    "options" = pkgs.stdenv.mkDerivation {
      name = "options";
      version = "v5.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-options.git";
        rev = "bc0109fb1a18d5f51aa32914618e96d1ec9d8cf5";
        sha256 = "1n25pp0xsxfdxsnfdjjwlxz79iam9kapx4al9aj24yi148xhqckl";
      };
    };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
      name = "ordered-collections";
      version = "v1.6.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-ordered-collections.git";
        rev = "54af8b281bf01acfc14e147debec76974901e93c";
        sha256 = "0r48p94d3cyzni2z7ikzcap472k23dx8zq37c1prmjb01v03mfvc";
      };
    };

    "orders" = pkgs.stdenv.mkDerivation {
      name = "orders";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-orders.git";
        rev = "80e22c22c72c846e09ef9dfcdb40b3eee39118d6";
        sha256 = "13p1sm4dxkmxhld9x5qqg62iiajjb3qpzs66c1r24y5fs4zsfry4";
      };
    };

    "parallel" = pkgs.stdenv.mkDerivation {
      name = "parallel";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-parallel.git";
        rev = "4d6c8b05041a36c300dfca2ba8f1f3443ca26bc6";
        sha256 = "1d5bnagabw2k8yxywkygwrpblb2ggqh2fhpqfrx2sj1y53x332hg";
      };
    };

    "partial" = pkgs.stdenv.mkDerivation {
      name = "partial";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-partial.git";
        rev = "76b63a324f7eafbb859256771b5bb7404082af96";
        sha256 = "11qr80989g7xmvw1brnrclsbg2wdkbr5k3cqpngfip3nnirrypcn";
      };
    };

    "prelude" = pkgs.stdenv.mkDerivation {
      name = "prelude";
      version = "v4.1.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-prelude.git";
        rev = "a96663b34364fdd0885a200955e35b99f4e58c43";
        sha256 = "1frvjrv0mr508r6683l1mp5rzm1y2dz76fz40zf4k2c64sy6y1xm";
      };
    };

    "proxy" = pkgs.stdenv.mkDerivation {
      name = "proxy";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-proxy.git";
        rev = "4a529b1f874fa2f32fc4c575cafaf46e0ab69fb6";
        sha256 = "0rqf25b1n9p5sgx7gdsxwrfv9rb3sqxgqmqpp5kdm30lfk7snz24";
      };
    };

    "quickcheck" = pkgs.stdenv.mkDerivation {
      name = "quickcheck";
      version = "v6.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-quickcheck.git";
        rev = "6289a80570acd5aec3ea89dc673cf10cdaf5794a";
        sha256 = "0b6208067krf81kzq2hbxs68386hcicbscwxbj5nck07ivjjvqh0";
      };
    };

    "random" = pkgs.stdenv.mkDerivation {
      name = "random";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-random.git";
        rev = "75e6b21edbe0eec78c28ff3bd8265998f2ea0b45";
        sha256 = "0k37v7z529adx6ypxj0xjyfrz45qia6p0vki2wpvi8lik7c698gf";
      };
    };

    "react-basic" = pkgs.stdenv.mkDerivation {
      name = "react-basic";
      version = "v13.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/lumihq/purescript-react-basic.git";
        rev = "bb3cfcbde081f75f4f3e1d04f0a83655f09af437";
        sha256 = "133kfzp78x6vd6v5b05ph9p08pj4mxiv28hrchv13hn0ndhhm6fx";
      };
    };

    "record" = pkgs.stdenv.mkDerivation {
      name = "record";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-record.git";
        rev = "42a15ba34d860f4d8f899836956bf09659a0256b";
        sha256 = "1l7ixb0gc2man36181g3hdf46sjp7xh0kv8bgrvalxfisjmd12v0";
      };
    };

    "refs" = pkgs.stdenv.mkDerivation {
      name = "refs";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-refs.git";
        rev = "e8b175477661e433175e76548168290c40e0ce4b";
        sha256 = "08161iy1xbafzblv033v84156azpcqkiw9v9d6gliphrq5fm17gm";
      };
    };

    "simple-json" = pkgs.stdenv.mkDerivation {
      name = "simple-json";
      version = "v7.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-simple-json.git";
        rev = "d6c4163f6ad65be97b148ebf86c900cb821da5a8";
        sha256 = "1x2f4zq1m9r3vg9hdpjld98jd56w7fss8fzvlrmnrw6xzd1gi456";
      };
    };

    "simple-json-utils" = pkgs.stdenv.mkDerivation {
      name = "simple-json-utils";
      version = "v0.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-simple-json-utils.git";
        rev = "ec5df413e1058959454e380de42f590046a43373";
        sha256 = "05mpvn3hrl86sapns88h7k9ccv29d8xmcnll8iz6ix5ibmh9vk2v";
      };
    };

    "st" = pkgs.stdenv.mkDerivation {
      name = "st";
      version = "v4.0.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-st.git";
        rev = "c1b9a0d47a5be1d7ea713ef1c583040eb332250a";
        sha256 = "0m2jkb9dmpbr8s1c20l7sm2q11y5rx8gqfiyspnyhq5apzkknjr0";
      };
    };

    "string-parsers" = pkgs.stdenv.mkDerivation {
      name = "string-parsers";
      version = "v5.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/paf31/purescript-string-parsers.git";
        rev = "ff023be7eeaf3dd129e652f9f1c225dfb196cf94";
        sha256 = "1lykswyd3icv9lx4r096lxfd244i0pzj2f4fpm604czzlfw6bspv";
      };
    };

    "strings" = pkgs.stdenv.mkDerivation {
      name = "strings";
      version = "v4.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-strings.git";
        rev = "94c843b93142d0edf1c31ec075c40b6984c3dc7b";
        sha256 = "147l3l3fzn7liparhm2y3p8j4ck1lblra5j493p2hy5yy5ndznc8";
      };
    };

    "tailrec" = pkgs.stdenv.mkDerivation {
      name = "tailrec";
      version = "v4.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tailrec.git";
        rev = "69f4625969e313203028968e4a9f743fa7f87883";
        sha256 = "0z7k80nl8dgv8mc2w8xsl2n0637bd1l8ppxak8kaifgjjwa81hx3";
      };
    };

    "test-unit" = pkgs.stdenv.mkDerivation {
      name = "test-unit";
      version = "v15.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/bodil/purescript-test-unit.git";
        rev = "351c55b632e0c0ebffae05837909995a03de3406";
        sha256 = "06lb90vppa7naqqwz7wbvlkkyz86pbdd3ycw3d2iygvxbzkz8xjn";
      };
    };

    "transformers" = pkgs.stdenv.mkDerivation {
      name = "transformers";
      version = "v4.2.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-transformers.git";
        rev = "0e473e5ef0e294615ca0d9aab0bcffee47b2870d";
        sha256 = "03qmvl9s7lbvm73dy9ps6qp39pdcm91hb8yakgj7aq8hgpj7b6bg";
      };
    };

    "tuples" = pkgs.stdenv.mkDerivation {
      name = "tuples";
      version = "v5.1.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tuples.git";
        rev = "0036bf9d99b721fd0f2e539d24e18e484b016927";
        sha256 = "045nsy0r2g51gih0wjhcvhl6gfr8947mlrqwg644ygz72rjm8wq4";
      };
    };

    "type-equality" = pkgs.stdenv.mkDerivation {
      name = "type-equality";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-type-equality.git";
        rev = "2cdae51c394401cd5fc04b03c341273b41532b7d";
        sha256 = "1b7szyca5s96gaawvgwrw7fa8r7gqsdff7xhz3vvngnylv2scl3w";
      };
    };

    "typelevel-prelude" = pkgs.stdenv.mkDerivation {
      name = "typelevel-prelude";
      version = "v5.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-typelevel-prelude.git";
        rev = "82b343fabfe3bf4ebf8106ce61bfe24fb3ed500c";
        sha256 = "01ki39xj87kwf8j8divlzwrvfyjcgxpmzhhmxzjylqx6jarcwyg6";
      };
    };

    "unfoldable" = pkgs.stdenv.mkDerivation {
      name = "unfoldable";
      version = "v4.0.2";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unfoldable.git";
        rev = "be3262a9dc48e794676b1b2883987331d4be6fd7";
        sha256 = "0lzhx030c5933maxcjwk6kzlvbxky1kiwrymqf1dp5wbrar3jyv4";
      };
    };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
      name = "unsafe-coerce";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unsafe-coerce.git";
        rev = "fa6a5ca9b4581c00ee0b8539306a49badb7bee60";
        sha256 = "0k9255mk2mz6xjb11pwkgfcblmmyvr86ig5kr92jwy95xim09zip";
      };
    };

    "unsafe-reference" = pkgs.stdenv.mkDerivation {
      name = "unsafe-reference";
      version = "v3.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-unsafe-reference";
        rev = "79d7de7b9351346a73e6c060d80532c95ba1c7c1";
        sha256 = "0q758dz59qz0li4s3w1qcg921xp5i5rh6i1l611iv7rr8cbj11al";
      };
    };

    "variant" = pkgs.stdenv.mkDerivation {
      name = "variant";
      version = "v6.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/natefaubion/purescript-variant.git";
        rev = "31e620334124d2ca8b1e608c27d74b607a5831e9";
        sha256 = "0cn227q57zbqm6r1aw5kvnp1x8zkc1x7wx28yyz311lmy7k1mkql";
      };
    };

    "web-dom" = pkgs.stdenv.mkDerivation {
      name = "web-dom";
      version = "v4.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-dom.git";
        rev = "0c47ae3e37407c10789712137381f7899d1ac3a0";
        sha256 = "14mssfhg81diy82wbv3ja8zk9a92267c6svq4bgfag91hydw4p42";
      };
    };

    "web-events" = pkgs.stdenv.mkDerivation {
      name = "web-events";
      version = "v2.0.1";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-events.git";
        rev = "7f19f24d7b61066bef0813734964f2dc6b085e3d";
        sha256 = "1vd1gfh6zv50bq4v1ppl2wvc5mskcw9n1bfj29qjg0dx0ffxzv2f";
      };
    };

    "web-file" = pkgs.stdenv.mkDerivation {
      name = "web-file";
      version = "v2.3.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-file.git";
        rev = "5245d62ba35357c6fb74fa919797d2b7c08110cd";
        sha256 = "08k0xv9zpg040v32k3wk66bhzx16c2nn9v35f01gq96anhm713s1";
      };
    };

    "web-html" = pkgs.stdenv.mkDerivation {
      name = "web-html";
      version = "v2.3.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-html.git";
        rev = "6f0d367f737202fdf9638f1f6836716c26456014";
        sha256 = "026y4kkrc2z4zmxlc4z21znq8knaqqjazf1ny811gm1507b1ykc6";
      };
    };

    "web-storage" = pkgs.stdenv.mkDerivation {
      name = "web-storage";
      version = "v3.0.0";
      fetched = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-storage.git";
        rev = "c2dedea1ee10ca7e94af5547c90274fb63ab3bc6";
        sha256 = "1ycb2s29aw9w6lqik6hfmp9nf9i2yhn0q26hc4p3450jam5mj8bx";
      };
    };
}
